coisa = input('digite alguma coisa: ')
print(type(coisa))
print(f'tem somente espaços? {coisa.isspace()}')
print(f'É um número? {coisa.isnumeric()}')
print(f'É alfabetico? {coisa.isalpha()}')
print(f'É alfanúmerico? {coisa.isalnum()}')
print(f'Está em maiusculas? {coisa.isupper()}')
print(f'Está em ninusculas? {coisa.islower()}')
print(f'Está capitalizada? {coisa.istitle()}')
